import type { Locale } from "./i18n";

const fr = {
  nav: { home: "Accueil", offers: "Offres", cases: "Références", method: "Méthode", about: "À propos", contact: "Contact", book: "Réserver 30 min" },
  switchTo: "en",
  brandSub: "Produits IA · de bout en bout",

  home: {
    eyebrow: "Ingénieur produit IA indépendant — Casablanca · fuseau de Paris",
    h1a: "Des produits IA entiers — ",
    h1em: "du scraper",
    h1b: " à la facture.",
    lead: "La démo, tout le monde sait la faire. Ce qui bloque, c’est le reste : le multi-tenant, les droits, les quotas, le coût par requête, l’audit, les files d’attente, l’évaluation. J’ai construit ça seul, et c’est en production.",
    ctaPrimary: "Réserver 30 minutes",
    ctaSecondary: "Les trois offres",
    priceLine: "Projets à partir de 12 000 € · TJM 600 € · disponible immédiatement",

    scoreLabel: "Compté dans le code — BidTender, en production depuis sept. 2025",
    score: [
      { v: "84", l: "routeurs d’API en production", hi: false },
      { v: "300", l: "modules métier", hi: false },
      { v: "274 376", l: "citations de provenance", hi: false },
      { v: "1", l: "personne, du scraper à la facture", hi: true },
    ],

    demo: {
      label: "Démonstration — CPS n° 42/2025 · 312 pages · FR/AR scanné",
      queryLabel: "Requête",
      query: "Quelle caution provisoire, et avant quelle date ?",
      answerLabel: "Réponse",
      sourceOf: "Source",
      answer: [
        { t: "La caution provisoire est fixée à " },
        { t: "150 000,00 DH", ref: 1 },
        { t: ", à déposer au plus tard le " },
        { t: "14 novembre 2025 à 10 h", ref: 2 },
        { t: ". L’agrément exigé est le " },
        { t: "secteur E — classe 3", ref: 3 },
        { t: "." },
      ] as { t: string; ref?: number }[],
      tally: "3 valeurs · 3 sources · 0 non sourcée",
      sourcesLabel: "Sources — cliquez une citation",
      sources: [
        { n: 1, doc: "CPS · Art. 9 · page 42", meta: "PDF natif · conf. 1.00",
          quote: "Le montant du cautionnement provisoire est fixé à cent cinquante mille dirhams (150 000,00 DH)." },
        { n: 2, doc: "Avis d’appel d’offres · page 1", meta: "Scan · OCR · conf. 0.97",
          quote: "Les plis devront être déposés au bureau des marchés avant le 14/11/2025 à 10 h 00." },
        { n: 3, doc: "Règlement de consultation · Art. 4", meta: "Scan AR/FR · conf. 0.91",
          quote: "Justifier de la qualification et classification : secteur E, classe 3, qualification E2." },
      ],
      note: "Démonstration reconstituée à partir d’un dossier type, valeurs anonymisées — ce n’est pas un document client. En production : 274 376 citations sur 58 champs, dont 99,95 % avec le passage verbatim.",
    },

    problemTitle: "Pourquoi une démo IA ne devient pas un produit",
    problemLead: "Trois raisons, et aucune n’est le modèle.",
    problems: [
      { title: "Elle n’a qu’un seul utilisateur",
        body: "Une démo tourne pour vous. Un produit tourne pour des clients qui ne doivent jamais se voir. L’isolation se joue en base, dans la requête elle-même — l’implémentation naïve qui cherche partout puis filtre est sécurisée, et cassée : le rappel s’effondre à mesure que la base grossit, et le bug n’apparaît jamais en démo mono-client." },
      { title: "Personne ne sait ce qu’elle coûte",
        body: "Tant que c’est une démo, la facture du modèle est une ligne perdue. En production, c’est votre marge. Il faut un coût connu par requête et par client, des quotas, des plafonds, une alerte de dépassement — et un routage qui envoie les questions simples vers un modèle bien moins cher, sans que personne ne s’en aperçoive." },
      { title: "Personne ne sait si elle a raison",
        body: "« Est-ce que c’est meilleur ? » jugé à l’œil sur quelques requêtes familières n’est pas une réponse. Il faut un jeu annoté qui vous appartient, une vérification des réponses contre leurs sources, et le droit de dire « cette information n’est pas dans le dossier » — le seul mode de défaillance vraiment grave, c’est le système qui répond toujours." },
    ],

    pipelineTitle: "La chaîne complète",
    pipelineLead: "— ce que « du scraper à la facture » veut dire concrètement",
    pipeline: [
      { t: "Acquisition", d: "Aller chercher la donnée là où il n’y a pas d’API. 45 000 fichiers, 56 Go." },
      { t: "Compréhension", d: "OCR bilingue routé page par page. 1,1 M de mots situés." },
      { t: "Décision", d: "58 champs extraits, scoring, inférence — la source à côté.", hi: true },
      { t: "Restitution", d: "Interface, exports, documents et présentations générés." },
      { t: "Droits", d: "Isolation en base par locataire, matrice (fonction, rôle)." },
      { t: "Facturation", d: "Plans, compteurs d’usage, quotas, factures." },
    ],

    offerTitle: "Trois offres, pas un catalogue",
    offerLead: "Chacune répond à un moment précis. Si votre situation ne rentre dans aucune des trois, je vous le dis au premier appel.",
    offersAll: "Le détail des trois offres",
    offers: [
      { title: "De la démo à la production", price: "14 000 – 22 000 € · 4 à 6 semaines",
        body: "Votre POC marche sur un ordinateur et personne n’ose le mettre devant des clients. J’ajoute ce qui manque pour qu’il devienne vendable : isolation, droits, quotas, coût maîtrisé, évaluation, garde-fous, observabilité." },
      { title: "Le produit entier", price: "30 000 – 55 000 € · 2 à 4 mois",
        body: "Vous voulez un produit IA et vous n’avez pas d’équipe. Acquisition, traitement, base, IA, interface, droits, facturation, mise en production. Une seule personne responsable de la chaîne." },
      { title: "Le socle documents", price: "9 000 – 15 000 € · 3 à 4 semaines",
        body: "Vos documents sont lourds, scannés, multilingues, contractuels, et l’IA répond à côté ou sans preuve. Ingestion, OCR, recherche hybride, citations vérifiables, jeu d’évaluation qui vous appartient." },
    ],

    refsTitle: "Quatre références",
    refsAll: "Tout voir",
    ctaTitle: "Une démo qui marche. Et après ?",
    ctaBody: "Décrivez la situation en trois lignes — ce qui existe déjà, ce qui doit exister, et pour quand. Je vous dis en trente minutes dans laquelle des trois offres ça tombe, ou si ce n’est pas pour moi. Réponse sous 24 h en semaine.",
  },

  offersPage: {
    title: "Trois offres",
    lead: "Une ligne d’accroche ne dit pas ce qu’on achète. Voici les trois seules choses que je vends, avec leur prix, leur durée et la question que je poserai au premier appel.",
    whoLabel: "Pour qui",
    deliverLabel: "Ce que je livre",
    qualLabel: "La question que je pose",
    items: [
      {
        n: "01",
        title: "De la démo à la production",
        price: "14 000 – 22 000 €",
        duration: "4 à 6 semaines",
        who: "Vous avez un POC IA qui marche. Personne n’ose le mettre devant des clients : on ne sait pas ce qu’il coûterait à l’échelle, ni ce qui se passe si un utilisateur voit les données d’un autre.",
        deliver: [
          "Isolation multi-tenant réelle — au niveau de la base et de la requête, pas de l’interface — et matrice de droits (fonction, rôle).",
          "Quotas, compteurs d’usage, plafonds et alertes de dépassement.",
          "Routage des modèles par coût, et suivi de la dépense par requête et par client.",
          "Harnais d’évaluation : jeu annoté qui vous appartient, score de fidélité aux sources, détection de régression.",
          "Garde-fous : filtrage des tentatives d’injection dans les documents, journal d’audit, masquage des données sensibles.",
          "Traitements longs en file d’attente, avec reprise et progression en temps réel.",
          "Observabilité : traces, journaux, alertes — et une astreinte de transition de deux semaines.",
        ],
        qual: "Votre POC, aujourd’hui, il tourne sur quoi et qui peut le casser ?",
      },
      {
        n: "02",
        title: "Le produit entier",
        price: "30 000 – 55 000 €",
        duration: "2 à 4 mois · ou 6 500 – 8 000 € par mois en régie",
        who: "Une équipe qui veut un produit IA et n’a pas d’équipe technique pour le porter. Aujourd’hui l’alternative est une agence à trois fois le prix, ou trois indépendants qui ne se parlent pas.",
        deliver: [
          "L’acquisition de la donnée, y compris quand il n’y a pas d’API : scraping, imports, connecteurs.",
          "Le traitement : OCR, extraction structurée, normalisation, contrôle de cohérence.",
          "La base et le modèle de données, avec l’isolation et les droits pensés dès la première migration.",
          "La couche IA : recherche, génération, évaluation, garde-fous, contrôle du coût.",
          "L’interface avec laquelle vos utilisateurs travaillent réellement, et l’onboarding qui va avec.",
          "La facturation : plans, abonnements, compteurs, factures.",
          "La mise en production, l’observabilité, et la documentation pour que quelqu’un d’autre puisse reprendre.",
        ],
        qual: "Qu’est-ce qui doit exister dans 90 jours pour que ce soit un succès ?",
      },
      {
        n: "03",
        title: "Le socle documents",
        price: "9 000 – 15 000 €",
        duration: "3 à 4 semaines",
        who: "Vos documents sont lourds, scannés, multilingues et juridiquement engageants. Vous avez branché un LLM dessus et il répond à côté, ou sans preuve.",
        deliver: [
          "Ingestion multi-format et routage OCR page par page — on ne paie l’OCR que là où il est nécessaire.",
          "Découpage par unité de sens et non par fenêtre de tokens.",
          "Recherche hybride lexicale et vectorielle, parce qu’aucune des deux seule ne suffit sur un corpus formulaire.",
          "Citations vérifiables : chaque valeur rattachée à l’extrait verbatim qui l’a produite.",
          "Le jeu d’évaluation annoté, le protocole d’échantillonnage et le code de scoring — ils vous appartiennent.",
          "Le tableau de bord de qualité, pour juger le système sans moi.",
        ],
        qual: "Comment savez-vous aujourd’hui qu’une réponse est juste ?",
      },
    ],
    howTitle: "Comment ça se passe",
    how: [
      "**Trente minutes, gratuites.** Vous décrivez la situation, je vous dis dans quelle offre ça tombe — ou que ce n’est pas pour moi. Pas de présentation commerciale.",
      "**Une proposition écrite sous 48 h.** Périmètre, livrables, date de livraison ferme, prix fixe. Pas de régie déguisée.",
      "**40 % à la commande, le solde à la livraison.** Paiement à 30 jours. La propriété intellectuelle vous est transférée au paiement intégral.",
      "**Un point par semaine, et l’accès au dépôt en continu.** Vous voyez le code avancer, vous n’attendez pas une démonstration finale.",
    ],
    notTitle: "Ce que je ne fais pas",
    notBody: "Pas de marchés publics ni d’achats — c’est le domaine de ma propre société. Pas de jumeau numérique ni d’IA industrielle — c’est celui de mon employeur. Pas de mission où personne ne peut me dire comment on saura que ça a marché. Et pas de renfort dans une équipe existante : je prends la responsabilité d’un périmètre, pas une place dans un planning.",
    ctaTitle: "Dans laquelle des trois vous reconnaissez-vous ?",
    ctaBody: "Si vous hésitez entre deux, c’est en général la première. Trente minutes suffisent pour trancher.",
  },

  method: {
    title: "La méthode",
    lead: "Cinq principes, tous appris en cassant quelque chose.",
    items: [
      { title: "Le jeu d’évaluation avant le pipeline",
        body: "30 dossiers stratifiés, 8 champs critiques, 240 cellules annotées à la main, échantillon tiré de façon déterministe pour être rejouable. Sans ça, « est-ce que c’est meilleur ? » se juge à l’œil sur quelques requêtes familières. Je l’ai fait après. Je le referais en premier." },
      { title: "Le coût est une fonctionnalité, pas une ligne de facture",
        body: "Toutes les questions ne méritent pas le même modèle. Classer l’intention d’une question coûte quelques dizaines de jetons et permet d’envoyer les demandes factuelles vers un palier bien moins cher — chez moi, un rapport d’environ cinquante à un. Ça se met derrière un interrupteur, ça se mesure par client, et ça se coupe sans redéploiement si la qualité bouge." },
      { title: "Combien de votre information vit dans des tableaux ?",
        body: "C’est ma première question sur un corpus inconnu, et la réponse change le plan de charge du simple au double. Le texte au fil de l’eau se règle vite ; les 228 771 lignes de bordereau de prix ont demandé une chaîne de traitement entièrement séparée, parce que dans une grille la structure est l’information." },
      { title: "Le silence est un objectif produit",
        body: "Un système qui répond toujours est un système qui invente parfois — le seul mode de défaillance vraiment grave sur une pièce contractuelle. Faire de « cette information n’est pas dans le dossier » une réponse correcte et assumée est autant un travail d’interface que de modèle." },
      { title: "Cadrage au périmètre, pas aux jours",
        body: "« Livré le 30 » est une promesse que je peux tenir. « Deux jours par semaine » est une promesse que les imprévus font casser. Le cadrage se fait au livrable et à la date : c’est ce qui vous donne une date ferme plutôt qu’une disponibilité théorique." },
    ],
    sectorsTitle: "Secteurs",
    sectors: [
      { t: "Legal-tech", d: "Contrats, extraction de clauses, dossiers" },
      { t: "Assurance", d: "Sinistres, comparaison de garanties" },
      { t: "Santé et administration", d: "Dossiers, codage, conformité" },
      { t: "Documentation technique", d: "Manuels, normes, spécifications" },
      { t: "Finance", d: "Rapports, dépôts réglementaires, due diligence" },
    ],
    sectorsNote: "Le secteur compte moins que la situation : une donnée d’entrée que personne n’a envie de toucher, un enjeu qui interdit l’à-peu-près, et une équipe trop petite pour recruter trois spécialistes.",
  },

  cases: {
    title: "Références",
    lead: "Ce qui a été construit, dans quelles contraintes, et ce que je referais autrement.",
    client: "Client", built: "Ce qui a été construit", proof: "La preuve",
    role: "Rôle", period: "Période", stack: "Stack", results: "Résultats", visit: "Voir le produit",
    back: "Toutes les références", next: "Référence suivante",
  },

  about: {
    title: "À propos",
    lead: "Ingénieur IA, formé à Centrale, basé à Casablanca. Je construis des produits IA entiers — de la donnée qu’il faut aller chercher jusqu’à la facture qu’on envoie au client.",
    body: [
      "J’ai passé les deux dernières années sur deux systèmes qui devaient tourner pour de vrai : un SaaS multi-tenant de réponse aux marchés publics, dont je suis co-fondateur, et une plateforme de jumeau numérique pour une unité industrielle. Dans les deux cas, la partie intéressante n’a jamais été le modèle. C’est ce qui se passe quand la donnée d’entrée est laide, quand un flux tombe, quand un document fait quatre cents pages, et quand il faut quand même facturer quelqu’un à la fin du mois.",
      "Sur le premier, j’ai écrit et j’exploite 84 routeurs d’API et 300 modules métier : le scraping quotidien qui va chercher la donnée, l’OCR bilingue, la recherche citable, l’extraction structurée, les moteurs de décision, la génération de documents, l’isolation par locataire en base, le routage des modèles par coût, l’audit et la facturation. Seul. C’est ce qui me distingue : pas une technique, un périmètre.",
      "Cinq projets, cinq fois le même geste : une source que personne n’a envie de toucher — un site sans API, cinq protocoles industriels, des PDF scannés en deux langues — transformée en produit qui tourne, avec une base, des droits et une interface. C’est utile aux équipes trop petites pour recruter trois spécialistes, et à celles qui ont déjà un prototype qui ne passe pas à l’échelle.",
      "Je travaille en missions cadrées, à distance, en français ou en anglais. Le cadrage se fait au périmètre et à la date de livraison, pas au nombre de jours par semaine — c’est ce qui vous donne une date ferme plutôt qu’une disponibilité théorique.",
    ],
    factsTitle: "En bref",
    facts: [
      ["Formation", "École Centrale Casablanca — Data Science & Digitalisation · échange à CentraleSupélec"],
      ["Langues", "Français (DALF C1) · Anglais (TOEIC 885) · Arabe (langue maternelle)"],
      ["Basé à", "Casablanca — même fuseau horaire que Paris"],
      ["Disponibilité", "Immédiate — missions à distance"],
      ["Facturation", "Statut auto-entrepreneur marocain, facturation en euros"],
    ],
    notTitle: "Ce que je ne fais pas",
    notBody: "Pas de marchés publics ni d’achats — c’est le domaine de ma propre société. Pas de jumeau numérique ni d’IA industrielle — c’est celui de mon employeur. Et pas de projet où personne ne peut me dire comment on saura que ça a marché.",
  },

  contact: {
    title: "Parlons-en",
    lead: "Trente minutes suffisent pour savoir dans laquelle des trois offres votre situation tombe, et à quel prix. Pas de présentation commerciale — vous décrivez ce qui existe, je vous dis ce que j’en pense.",
    bookCta: "Réserver un créneau",
    orEmail: "Ou écrivez-moi",
    helpTitle: "Pour que le premier appel serve à quelque chose",
    help: [
      "Ce qui existe déjà : un prototype, un produit en ligne, ou rien du tout ?",
      "D’où vient la donnée, et dans quel état elle arrive.",
      "Qui s’en sert, et ce qui les bloque aujourd’hui.",
      "Votre échéance, et votre ordre de grandeur budgétaire.",
    ],
    replyTitle: "Réponse",
    replyBody: "Sous 24 h en semaine. Si votre besoin ne rentre pas dans ce que je fais, je vous le dis tout de suite et j’essaie de vous orienter.",
  },

  footer: { tagline: "Produits IA de bout en bout — du scraper à la facture.", rights: "Tous droits réservés." },
};

type Dict = typeof fr;

const en: Dict = {
  nav: { home: "Home", offers: "Offers", cases: "Work", method: "Method", about: "About", contact: "Contact", book: "Book 30 min" },
  switchTo: "fr",
  brandSub: "AI products · end to end",

  home: {
    eyebrow: "Independent AI product engineer — Casablanca · on Paris time",
    h1a: "Whole AI products — ",
    h1em: "from the scraper",
    h1b: " to the invoice.",
    lead: "Everyone can build the demo. What stops it is the rest: multi-tenancy, permissions, quotas, cost per request, audit trails, job queues, evaluation. I built all of that alone, and it runs in production.",
    ctaPrimary: "Book 30 minutes",
    ctaSecondary: "The three offers",
    priceLine: "Projects from €12,000 · Day rate €600 · available now",

    scoreLabel: "Counted in the code — BidTender, in production since Sept. 2025",
    score: [
      { v: "84", l: "API routers in production", hi: false },
      { v: "300", l: "business-logic modules", hi: false },
      { v: "274,376", l: "provenance citations", hi: false },
      { v: "1", l: "person, from the scraper to the invoice", hi: true },
    ],

    demo: {
      label: "Demo — tender file no. 42/2025 · 312 pages · FR/AR scanned",
      queryLabel: "Query",
      query: "What is the bid bond, and by what date?",
      answerLabel: "Answer",
      sourceOf: "Source",
      answer: [
        { t: "The bid bond is set at " },
        { t: "150,000.00 MAD", ref: 1 },
        { t: ", to be lodged no later than " },
        { t: "14 November 2025, 10:00", ref: 2 },
        { t: ". The required certification is " },
        { t: "sector E — class 3", ref: 3 },
        { t: "." },
      ] as { t: string; ref?: number }[],
      tally: "3 values · 3 sources · 0 unsourced",
      sourcesLabel: "Sources — click a citation",
      sources: [
        { n: 1, doc: "Specification · Art. 9 · page 42", meta: "Native PDF · conf. 1.00",
          quote: "The amount of the provisional bond is set at one hundred and fifty thousand dirhams (150,000.00 MAD)." },
        { n: 2, doc: "Tender notice · page 1", meta: "Scan · OCR · conf. 0.97",
          quote: "Bids must be lodged at the procurement office before 14/11/2025 at 10:00." },
        { n: 3, doc: "Consultation rules · Art. 4", meta: "Scan AR/FR · conf. 0.91",
          quote: "Evidence of qualification and classification required: sector E, class 3, qualification E2." },
      ],
      note: "A reconstructed demo built from a typical file, values anonymised — this is not a client document. In production: 274,376 citations across 58 fields, 99.95% of them carrying the verbatim passage.",
    },

    problemTitle: "Why an AI demo doesn’t become a product",
    problemLead: "Three reasons, and none of them is the model.",
    problems: [
      { title: "It only has one user",
        body: "A demo runs for you. A product runs for customers who must never see each other. Isolation belongs in the database, inside the query itself — the naive implementation that searches everything and then filters is secure, and broken: recall collapses as the corpus grows, and the bug never shows up in a single-tenant demo." },
      { title: "Nobody knows what it costs",
        body: "While it’s a demo, the model bill is a rounding error. In production it’s your margin. You need a known cost per request and per customer, quotas, ceilings, an overrun alert — and routing that sends simple questions to a far cheaper tier without anyone noticing." },
      { title: "Nobody knows whether it’s right",
        body: "“Is this better?” judged by eye on a handful of familiar queries is not an answer. You need an annotated set that belongs to you, verification of answers against their sources, and the right to say “that information is not in this file” — because the only truly serious failure mode is a system that always answers." },
    ],

    pipelineTitle: "The whole chain",
    pipelineLead: "— what “from the scraper to the invoice” actually means",
    pipeline: [
      { t: "Acquisition", d: "Getting data where there is no API. 45,000 files, 56 GB." },
      { t: "Understanding", d: "Bilingual OCR routed page by page. 1.1 M located words." },
      { t: "Decision", d: "58 extracted fields, scoring, inference — source alongside.", hi: true },
      { t: "Delivery", d: "Interface, exports, generated documents and decks." },
      { t: "Permissions", d: "Per-tenant isolation in the database, (feature, role) matrix." },
      { t: "Billing", d: "Plans, usage counters, quotas, invoices." },
    ],

    offerTitle: "Three offers, not a catalogue",
    offerLead: "Each answers a specific moment. If your situation fits none of the three, I’ll say so on the first call.",
    offersAll: "The three offers in detail",
    offers: [
      { title: "From demo to production", price: "€14,000 – 22,000 · 4 to 6 weeks",
        body: "Your POC works on a laptop and nobody dares put it in front of customers. I add what’s missing to make it sellable: isolation, permissions, quotas, controlled cost, evaluation, guardrails, observability." },
      { title: "The whole product", price: "€30,000 – 55,000 · 2 to 4 months",
        body: "You want an AI product and you have no team. Acquisition, processing, database, AI, interface, permissions, billing, production. One person accountable for the whole chain." },
      { title: "The document foundation", price: "€9,000 – 15,000 · 3 to 4 weeks",
        body: "Your documents are heavy, scanned, multilingual, contractual, and the AI answers beside the point or without proof. Ingestion, OCR, hybrid retrieval, verifiable citations, an evaluation set that belongs to you." },
    ],

    refsTitle: "Four references",
    refsAll: "See all",
    ctaTitle: "The demo works. Now what?",
    ctaBody: "Describe the situation in three lines — what already exists, what has to exist, and by when. In thirty minutes I’ll tell you which of the three offers it falls into, or that it isn’t for me. Reply within 24 hours on weekdays.",
  },

  offersPage: {
    title: "Three offers",
    lead: "A tagline doesn’t say what you’re buying. Here are the only three things I sell, with their price, their duration, and the question I’ll ask on the first call.",
    whoLabel: "Who it’s for",
    deliverLabel: "What I deliver",
    qualLabel: "The question I ask",
    items: [
      {
        n: "01",
        title: "From demo to production",
        price: "€14,000 – 22,000",
        duration: "4 to 6 weeks",
        who: "You have an AI POC that works. Nobody dares put it in front of customers: no one knows what it would cost at scale, or what happens if one user sees another’s data.",
        deliver: [
          "Real multi-tenant isolation — at the database and query level, not the interface — and a (feature, role) permission matrix.",
          "Quotas, usage counters, ceilings and overrun alerts.",
          "Cost-based model routing, and spend tracked per request and per customer.",
          "An evaluation harness: an annotated set that belongs to you, a groundedness score, regression detection.",
          "Guardrails: filtering of injection attempts hidden in documents, an audit log, redaction of sensitive data.",
          "Long jobs on a queue, with resume and live progress.",
          "Observability: traces, logs, alerts — and a two-week handover watch.",
        ],
        qual: "What is your POC running on today, and who can break it?",
      },
      {
        n: "02",
        title: "The whole product",
        price: "€30,000 – 55,000",
        duration: "2 to 4 months · or €6,500 – 8,000 per month on retainer",
        who: "A team that wants an AI product and has no engineering team to carry it. Today the alternative is an agency at three times the price, or three freelancers who don’t talk to each other.",
        deliver: [
          "Data acquisition, including where there is no API: scraping, imports, connectors.",
          "Processing: OCR, structured extraction, normalisation, consistency checks.",
          "The database and data model, with isolation and permissions designed into the first migration.",
          "The AI layer: retrieval, generation, evaluation, guardrails, cost control.",
          "The interface your users actually work in, and the onboarding that goes with it.",
          "Billing: plans, subscriptions, counters, invoices.",
          "Production deployment, observability, and documentation so somebody else can take over.",
        ],
        qual: "What has to exist in 90 days for this to be a success?",
      },
      {
        n: "03",
        title: "The document foundation",
        price: "€9,000 – 15,000",
        duration: "3 to 4 weeks",
        who: "Your documents are heavy, scanned, multilingual and legally binding. You pointed an LLM at them and it answers beside the point, or without proof.",
        deliver: [
          "Multi-format ingestion and page-by-page OCR routing — you only pay for OCR where it is needed.",
          "Chunking by unit of meaning rather than by token window.",
          "Hybrid lexical and vector retrieval, because neither alone is enough on a boilerplate corpus.",
          "Verifiable citations: every value tied to the verbatim passage that produced it.",
          "The annotated evaluation set, the sampling protocol and the scoring code — they belong to you.",
          "The quality dashboard, so you can judge the system without me.",
        ],
        qual: "How do you know today that an answer is correct?",
      },
    ],
    howTitle: "How it works",
    how: [
      "**Thirty minutes, free.** You describe the situation, I tell you which offer it falls into — or that it isn’t for me. No sales deck.",
      "**A written proposal within 48 hours.** Scope, deliverables, a firm delivery date, a fixed price. Not a retainer in disguise.",
      "**40 % on signature, the balance on delivery.** Payment within 30 days. Intellectual property transfers to you on full payment.",
      "**A weekly checkpoint, and repository access throughout.** You watch the code move; you don’t wait for a final demo.",
    ],
    notTitle: "What I don’t do",
    notBody: "No public procurement or tendering — that’s my own company’s field. No digital twins or industrial AI — that’s my employer’s. No engagement where nobody can tell me how we’ll know it worked. And no extra pair of hands inside an existing team: I take responsibility for a scope, not a slot in a schedule.",
    ctaTitle: "Which of the three do you recognise?",
    ctaBody: "If you’re hesitating between two, it’s usually the first. Thirty minutes is enough to settle it.",
  },

  method: {
    title: "The method",
    lead: "Five principles, every one of them learned by breaking something.",
    items: [
      { title: "The evaluation set before the pipeline",
        body: "30 stratified files, 8 critical fields, 240 cells annotated by hand, sample drawn deterministically so it can be replayed. Without it, “is this better?” is judged by eye on a handful of familiar queries. I did it afterwards. I’d do it first." },
      { title: "Cost is a feature, not a line on an invoice",
        body: "Not every question deserves the same model. Classifying a question’s intent costs a few dozen tokens and lets factual requests go to a far cheaper tier — in my case roughly fifty to one. It sits behind a switch, it is measured per customer, and it can be turned off without a redeploy if quality moves." },
      { title: "How much of your information lives in tables?",
        body: "It’s my first question on an unfamiliar corpus, and the answer doubles or halves the estimate. Flowing text settles quickly; 228,771 price-schedule rows needed an entirely separate processing chain, because in a grid the structure is the information." },
      { title: "Silence is a product goal",
        body: "A system that always answers is a system that sometimes invents — the only truly serious failure mode on a contractual document. Making “that information is not in this file” a correct, deliberate answer is as much interface work as model work." },
      { title: "Scope by deliverable, not by days",
        body: "“Delivered on the 30th” is a promise I can keep. “Two days a week” is a promise the unexpected breaks. Scoping happens by deliverable and date: that is what gets you a firm date instead of a theoretical availability." },
    ],
    sectorsTitle: "Sectors",
    sectors: [
      { t: "Legal tech", d: "Contracts, clause extraction, case files" },
      { t: "Insurance", d: "Claims, policy and coverage comparison" },
      { t: "Healthcare and admin", d: "Records, coding, compliance" },
      { t: "Technical documentation", d: "Manuals, standards, specifications" },
      { t: "Finance", d: "Reports, regulatory filings, due diligence" },
    ],
    sectorsNote: "The sector matters less than the situation: an input nobody wants to touch, stakes that rule out approximation, and a team too small to hire three specialists.",
  },

  cases: {
    title: "Work",
    lead: "What was built, under which constraints, and what I’d do differently.",
    client: "Client", built: "What was built", proof: "The proof",
    role: "Role", period: "Period", stack: "Stack", results: "Results", visit: "Visit the product",
    back: "All work", next: "Next case",
  },

  about: {
    title: "About",
    lead: "AI engineer, Centrale-trained, based in Casablanca. I build whole AI products — from the data you have to go and fetch, to the invoice you send the customer.",
    body: [
      "I’ve spent the last two years on two systems that had to run for real: a multi-tenant SaaS for public-procurement responses, which I co-founded, and a digital-twin platform for an industrial plant. In both cases the interesting part was never the model. It’s what happens when the input data is ugly, when a stream drops, when a document runs four hundred pages — and when you still have to invoice somebody at the end of the month.",
      "On the first one, I wrote and I operate 84 API routers and 300 business-logic modules: the daily scraping that fetches the data, bilingual OCR, citable retrieval, structured extraction, decision engines, document generation, per-tenant isolation in the database, cost-based model routing, audit and billing. Alone. That is what sets me apart: not a technique, a scope.",
      "Five projects, five times the same move: a source nobody wants to touch — a site with no API, five industrial protocols, scanned PDFs in two languages — turned into a product that runs, with a database, permissions and an interface. That’s useful to teams too small to hire three specialists, and to teams who already have a prototype that won’t scale.",
      "I work in scoped engagements, remote, in French or English. Scoping is done by deliverable and delivery date rather than days per week — which is what gets you a firm date instead of a theoretical availability.",
    ],
    factsTitle: "At a glance",
    facts: [
      ["Education", "École Centrale Casablanca — Data Science & Digitalisation · exchange at CentraleSupélec"],
      ["Languages", "French (DALF C1) · English (TOEIC 885) · Arabic (native)"],
      ["Based in", "Casablanca — same time zone as Paris"],
      ["Availability", "Immediate — remote engagements"],
      ["Invoicing", "Moroccan sole-trader status, invoices in euros"],
    ],
    notTitle: "What I don’t do",
    notBody: "No public procurement or tendering — that’s my own company’s field. No digital twins or industrial AI — that’s my employer’s. And no project where nobody can tell me how we’ll know it worked.",
  },

  contact: {
    title: "Let’s talk",
    lead: "Thirty minutes is enough to establish which of the three offers your situation falls into, and what it costs. No sales deck — you describe what exists, I tell you what I think.",
    bookCta: "Book a slot",
    orEmail: "Or email me",
    helpTitle: "To make the first call worth it",
    help: [
      "What already exists: a prototype, a live product, or nothing at all?",
      "Where the data comes from, and what state it arrives in.",
      "Who uses it, and what stops them today.",
      "Your deadline, and a rough budget range.",
    ],
    replyTitle: "Response",
    replyBody: "Within 24 hours on weekdays. If your need doesn’t fit what I do, I’ll say so immediately and try to point you somewhere better.",
  },

  footer: { tagline: "End-to-end AI products — from the scraper to the invoice.", rights: "All rights reserved." },
};

export const content: Record<Locale, Dict> = { fr, en };
export type { Dict };
